### ISSUE TITLE
Get sensor readings from IPMI DCMI

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-collectd#5]
Our pre-FGCI hardware doesn't provide power consumption information via "ipmitool sensor". However, all nodes, both FGCI and pre-FGCI report it via "ipmitool dcmi power reading".  Or equivalently "ipmi-dcmi --get-system-power-statistics" if one prefers freeipmi to ipmitool. 

The ipmitool.sh script should be modified to gather power consumption via dcmi first.

I'm looking into it.

**Comment by martbhell** [comment]
Done in PR #6 Thanks!
